stages:
  - publish

.pre-release:
  only:
    refs: [ tags ]

lpm:publish:
  stage: publish
  when: manual
  script: |
    docker pull node:lts
    docker run --rm \
      -v ${PWD}:/project \
      -w /project \
      -e LPM_REGISTRY="${LPM_REGISTRY}" \
      -e LPM_USERNAME="${ZZB_LPM_USERNAME}" \
      -e LPM_EMAIL="${ZZB_LPM_EMAIL}" \
      -e LPM_PASSWORD="${LPM_PASSWORD}" \
      -e LPM_PASSWORD_BASE64="${ZZB_LPM_PASSWORD_BASE64}" \
      node:lts \
      bash -c './ci/lpm-publish.sh'
  tags:
    - iflyos-builder

npm:publish:
  stage: publish
  when: manual
  script: |
    docker pull node:lts
    docker run --rm \
      -v ${PWD}:/project \
      -w /project \
      -e NPMRC="//registry.npmjs.org/:_authToken=${NPM_TOKEN}" \
      -e PKG_NAME="@listenai/lisa_core" \
      node:lts \
      bash -c './ci/npm-publish.sh'
  tags:
    - iflyos-builder
